{
  "timestamp": "2025-05-13T03:53:01.893974",
  "tests_run": 0,
  "failures": 0,
  "errors": 1,
  "successful": false,
  "failures_details": [],
  "errors_details": [
    "(<ErrorHolder description='setUpClass (__main__.TestVoiceAssistantLaunch)'>, 'Traceback (most recent call last):\\n  File \"/Users/mac/.pyenv/versions/3.10.13/lib/python3.10/site-packages/pyttsx3/__init__.py\", line 20, in init\\n    eng = _activeEngines[driverName]\\n  File \"/Users/mac/.pyenv/versions/3.10.13/lib/python3.10/weakref.py\", line 137, in __getitem__\\n    o = self.data[key]()\\nKeyError: None\\n\\nDuring handling of the above exception, another exception occurred:\\n\\nTraceback (most recent call last):\\n  File \"/Users/mac/Documents/Cursor_SecondBrain_Release_Package/test_launch.py\", line 30, in setUpClass\\n    cls.assistant = VoiceAssistant()\\n  File \"/Users/mac/Documents/Cursor_SecondBrain_Release_Package/app_core/voice.py\", line 52, in __init__\\n    self._setup()\\n  File \"/Users/mac/Documents/Cursor_SecondBrain_Release_Package/app_core/voice.py\", line 65, in _setup\\n    self.engine = pyttsx3.init()\\n  File \"/Users/mac/.pyenv/versions/3.10.13/lib/python3.10/site-packages/pyttsx3/__init__.py\", line 22, in init\\n    eng = Engine(driverName, debug)\\n  File \"/Users/mac/.pyenv/versions/3.10.13/lib/python3.10/site-packages/pyttsx3/engine.py\", line 30, in __init__\\n    self.proxy = driver.DriverProxy(weakref.proxy(self), driverName, debug)\\n  File \"/Users/mac/.pyenv/versions/3.10.13/lib/python3.10/site-packages/pyttsx3/driver.py\", line 50, in __init__\\n    self._module = importlib.import_module(name)\\n  File \"/Users/mac/.pyenv/versions/3.10.13/lib/python3.10/importlib/__init__.py\", line 126, in import_module\\n    return _bootstrap._gcd_import(name[level:], package, level)\\n  File \"<frozen importlib._bootstrap>\", line 1050, in _gcd_import\\n  File \"<frozen importlib._bootstrap>\", line 1027, in _find_and_load\\n  File \"<frozen importlib._bootstrap>\", line 1006, in _find_and_load_unlocked\\n  File \"<frozen importlib._bootstrap>\", line 688, in _load_unlocked\\n  File \"<frozen importlib._bootstrap_external>\", line 883, in exec_module\\n  File \"<frozen importlib._bootstrap>\", line 241, in _call_with_frames_removed\\n  File \"/Users/mac/.pyenv/versions/3.10.13/lib/python3.10/site-packages/pyttsx3/drivers/nsss.py\", line 12, in <module>\\n    class NSSpeechDriver(NSObject):\\n  File \"/Users/mac/.pyenv/versions/3.10.13/lib/python3.10/site-packages/pyttsx3/drivers/nsss.py\", line 13, in NSSpeechDriver\\n    @objc.python_method\\nNameError: name \\'objc\\' is not defined\\n')"
  ]
}